services:

  lens:
    image: docker.verbis.dkfz.de/dashboard/dzif-explorer:latest
    environment:
      PUBLIC_BACKEND_URL: "http://localhost:8082/fhir"

  blaze:
    image: samply/blaze
    environment:
      BASE_URL: "http://localhost:8082"
    ports:
      - "8080:8082"
    volumes:
      - "blaze-data:/app/data"

volumes:
  blaze-data:
